[project]
name = "quackpipe"
version = "0.5.0"
requires-python = ">=3.12"
description = "A configuration-driven and programmatic ETL helper for DuckDB."
dependencies = [
    "pyyaml",
    "duckdb>=0.9.0",
    "pandas",
    "python-dotenv"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "testcontainers",
    "testcontainers-postgres",
    "testcontainers-kafka",
    "testcontainers-minio",
    "httpx",
    "ipdb"
]
lint = [
    "ruff"
]
postgres = ["psycopg"]
s3 = ["pyarrow"]
kafka = ["confluent-kafka"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
quackpipe = "quackpipe.cli:main"

