# =======================================================
# quackpipe Configuration Example
# =======================================================
# 'secret_name' refers to a bundle of secrets that the
# configured secret provider knows how to resolve.
# For the default EnvSecretProvider, it will look for env vars
# prefixed with the secret name (e.g., PG_PROD_HOST).
# =======================================================

sources:
  pg_main:
    type: postgres
    secret_name: "pg_prod"
    # Non-secret configuration
    port: 5432
    read_only: true
    # You can specify which tables to automatically create views for
    tables:
      - users
      - orders

  datalake:
    type: s3
    secret_name: "aws_datalake"
    # Non-secret configuration
    region: "us-east-1"

  ducklake:
    type: ducklake
    catalog:
      type: postgres
      host: localhost
      port: 5433
      database: catalog
      user: duckdb
      password: duckdb_password
    storage:
      type: s3
      access_key_id: minioadmin
      secret_access_key: minioadmin123
      use_ssl: false
      url_style: path
      region: us-east-1
      endpoint: "localhost:9000"
      path: "s3://lakehouse/"

  my_lake:
    type: ducklake
    # The DuckLake source has two main components: catalog and storage
    catalog:
      type: postgres
      secret_name: "pg_prod" # Re-uses the postgres credentials
    storage:
      type: s3
      secret_name: "aws_datalake" # Re-uses the S3 credentials
      path: "s3://my-data-lake-bucket/" # The root path for the data

  # Example 1: Connecting to Azure Blob Storage using a Connection String.
  azure_storage_cs:
    type: azure
    # The provider type for this authentication method.
    provider: connection_string
    # This secret_name will cause quackpipe to look for an environment variable
    # named 'AZURE_PROD_CS_CONNECTION_STRING'.
    secret_name: "azure_prod_cs"

  # Example 2: Connecting to Azure Blob Storage using a Service Principal.
  azure_storage_sp:
    type: azure
    provider: service_principal
    # This secret_name will cause quackpipe to look for environment variables
    # prefixed with 'AZURE_PROD_SP_'.
    secret_name: "azure_prod_sp"
    # The storage account name is required and can be placed here directly.
    account: "yourstorageaccountname"